### ISSUE TITLE
Add tests folder

### ISSUE THREAD

**Issue by peter279k** [jawira/skeleton#46]
As title, I think it should be good to initial a `tests` folder and `phounit.xml.dist` file and create a demonstration test classes.

Once this issue is accepted by repository owner, I'll be happy to work on that.

**Comment by jawira** [comment]
Sorry for the delay, I didn't implement this before because you can achieve the same with:

```console
$ vendor/bin/phpunit --generate-configuration
```

Also, I'm working on v2 and I will completely replace current solution with a simple Phing buildfile.

Nevertheless, thank you for your interest in my project :)
